spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:/import.sql
      schema-locations: classpath:/schema.sql
jws:
  sharedKey: 90b571f5-72b4-4e20-bc61-4929a871c4d0