spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
jws:
  sharedKey: 90b571f5-72b4-4e20-bc61-4929a871c4d0