INSERT INTO category (name)
VALUES ('Work'),
       ('Personal'),
       ('Shopping'),
       ('Health'),
       ('Home'),
       ('Study'),
       ('Entertainment'),
       ('Finance'),
       ('Fitness'),
       ('Travel'),
       ('Social'),
       ('Hobbies'),
       ('Family'),
       ('Friends'),
       ('Goals'),
       ('Events'),
       ('Reading'),
       ('Writing'),
       ('Cooking'),
       ('Tech');
INSERT INTO task (title, description, due_date, priority, status, category_id)
VALUES ('Finish Project Proposal', 'Review and finalize project proposal for client meeting', '2024-02-15', 'High',
        'To Do', 1),
       ('Buy Groceries', 'Purchase items for the week including fruits, vegetables, and bread', '2024-02-20', 'Medium',
        'In Progress', 3),
       ('Exercise', 'Go for a 30-minute jog in the morning', '2024-02-25', 'High', 'Done', 9),
       ('Book Flight Tickets', 'Book round-trip flight tickets for upcoming vacation', '2024-03-01', 'High', 'To Do',
        10),
       ('Read Chapter 5', 'Read Chapter 5 of "The Great Gatsby" for literature class', '2024-03-05', 'Medium',
        'In Progress', 6),
       ('Pay Bills', 'Pay utility bills and credit card bills', '2024-03-10', 'High', 'To Do', 8),
       ('Attend Yoga Class', 'Attend the 6 PM yoga class at the local studio', '2024-03-15', 'Medium', 'To Do', 4),
       ('Write Blog Post', 'Write a blog post on the latest technology trends', '2024-03-20', 'High', 'To Do', 12),
       ('Plan Weekend Trip', 'Plan a weekend getaway to the mountains', '2024-03-25', 'Medium', 'In Progress', 10),
       ('Call Mom', 'Call mom to catch up and share updates', '2024-03-30', 'Low', 'To Do', 13),
       ('Complete Online Course', 'Finish the last module of the online course on web development', '2024-04-05',
        'High', 'In Progress', 6),
       ('Attend Networking Event', 'Attend the local tech meetup for networking', '2024-04-10', 'Medium', 'Done', 10),
       ('Painting Session', 'Have a painting session to relax and unwind', '2024-04-15', 'Low', 'In Progress', 7),
       ('Update Resume', 'Update resume with recent achievements and projects', '2024-04-20', 'High', 'Done', 1),
       ('Organize Home Office', 'Declutter and organize the home office space', '2024-04-25', 'Medium', 'In Progress',
        5),
       ('Learn a New Recipe', 'Try cooking a new recipe for dinner', '2024-05-01', 'Low', 'To Do', 19),
       ('Start Book Club', 'Initiate a book club with friends and pick the first book', '2024-05-05', 'High', 'To Do',
        15),
       ('Practice Guitar', 'Spend 30 minutes practicing the guitar', '2024-05-10', 'Medium', 'Done', 11),
       ('Volunteer at Local Shelter', 'Offer time to volunteer at the local animal shelter', '2024-05-15', 'High',
        'To Do', 14),
       ('Visit Art Exhibition', 'Attend the art exhibition at the city gallery', '2024-05-20', 'Medium', 'Done', 6);
INSERT INTO address (street, city, zip_code)
VALUES ('123 Main St', 'New York', '10001'),
       ('456 Oak St', 'Los Angeles', '90001'),
       ('789 Pine St', 'Chicago', '60601'),
       ('101 Elm St', 'San Francisco', '94105'),
       ('202 Maple St', 'Houston', '77002'),
       ('303 Cedar St', 'Miami', '33101'),
       ('404 Birch St', 'Dallas', '75201'),
       ('505 Walnut St', 'Atlanta', '30301'),
       ('606 Spruce St', 'Seattle', '98101'),
       ('707 Ash St', 'Boston', '02101'),
       ('808 Pine St', 'Denver', '80202'),
       ('909 Oak St', 'Philadelphia', '19102'),
       ('1010 Maple St', 'Phoenix', '85001'),
       ('1111 Elm St', 'San Diego', '92101'),
       ('1212 Cedar St', 'Austin', '73301'),
       ('1313 Birch St', 'Portland', '97201'),
       ('1414 Walnut St', 'Nashville', '37201'),
       ('1515 Spruce St', 'San Antonio', '78201'),
       ('1616 Ash St', 'Las Vegas', '89101'),
       ('1717 Pine St', 'Minneapolis', '55401'),
       ('1818 Oak St', 'Detroit', '48201');

INSERT INTO members (name, surname, email, password, address_id)
VALUES ('John', 'Doe', 'admin@admin.com', '$2a$13$9kqnZ.VftG7t2z7R5LiVJeMDZ1/lWbbI/XjoNtoGsyvlupmKrBfri', 1),
       ('Jane', 'Smith', 'jane.smith@example.com', '$2a$12$d0oZz3ZRpKrYlvqIKM/OGuf9UGnqm4arvvFiJF.BVDKU8GggKS7NS', 2),
       ('Alice', 'Johnson', 'alice.johnson@example.com', '$2a$12$d0oZz3ZRpKrYlvqIKM/OGuf9UGnqm4arvvFiJF.BVDKU8GggKS7NS', 3),
       ('Bob', 'Miller', 'bob.miller@example.com', 'dqs', 4),
       ('Emily', 'Jones', 'emily.jones@example.com', 'password5', 5),
       ('David', 'Williams', 'david.williams@example.com', 'password6', 6),
       ('Olivia', 'Brown', 'olivia.brown@example.com', 'password7', 7),
       ('Michael', 'Taylor', 'michael.taylor@example.com', 'password8', 8),
       ('Sophia', 'Moore', 'sophia.moore@example.com', 'password9', 9),
       ('Daniel', 'Clark', 'daniel.clark@example.com', 'password10', 10),
       ('Emma', 'Lee', 'emma.lee@example.com', 'password11', 11),
       ('Matthew', 'White', 'matthew.white@example.com', 'password12', 12),
       ('Ava', 'Anderson', 'ava.anderson@example.com', 'password13', 13),
       ('William', 'Harris', 'william.harris@example.com', 'password14', 14),
       ('Ella', 'Martin', 'ella.martin@example.com', 'password15', 15),
       ('James', 'Thompson', 'james.thompson@example.com', 'password16', 16),
       ('Amelia', 'Garcia', 'amelia.garcia@example.com', 'password17', 17),
       ('Benjamin', 'Rodriguez', 'benjamin.rodriguez@example.com', 'password18', 18),
       ('Mia', 'Lopez', 'mia.lopez@example.com', 'password19', 19),
       ('Logan', 'Martinez', 'logan.martinez@example.com', 'password20', 20);
INSERT INTO assignment (task_id, members_id)
VALUES (1, 1),
       (2, 2),
       (2, 2),
       (2, 2),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20);

INSERT INTO role (name)
VALUES ('ADMIN'),
       ('USER');

INSERT INTO user_roles (members_id, role_id)
VALUES (1, 2),
       (2, 2),
       (3, 2);

INSERT INTO assignment (task_id, members_id)
VALUES (1, 1),
       (2, 2),
       (3, 1);