services:
  mysql:
      container_name: bazadanych
      image: mysql:8.2.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'