INSERT INTO category (name) VALUES ('Work');
INSERT INTO category (name) VALUES ('Personal');
INSERT INTO category (name) VALUES ('Shopping');
INSERT INTO category (name) VALUES ('Health');
INSERT INTO category (name) VALUES ('Home');
INSERT INTO category (name) VALUES ('Study');
INSERT INTO category (name) VALUES ('Entertainment');
INSERT INTO category (name) VALUES ('Finance');
INSERT INTO category (name) VALUES ('Fitness');
INSERT INTO category (name) VALUES ('Travel');
INSERT INTO category (name) VALUES ('Social');
INSERT INTO category (name) VALUES ('Hobbies');
INSERT INTO category (name) VALUES ('Family');
INSERT INTO category (name) VALUES ('Friends');
INSERT INTO category (name) VALUES ('Goals');
INSERT INTO category (name) VALUES ('Events');
INSERT INTO category (name) VALUES ('Reading');
INSERT INTO category (name) VALUES ('Writing');
INSERT INTO category (name) VALUES ('Cooking');
INSERT INTO category (name) VALUES ('Tech');

INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Finish Project Proposal', 'Review and finalize project proposal for client meeting', '2024-02-15', 'High', 'To Do', 1);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Buy Groceries', 'Purchase items for the week including fruits, vegetables, and bread', '2024-02-20', 'Medium', 'In Progress', 3);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Exercise', 'Go for a 30-minute jog in the morning', '2024-02-25', 'High', 'Done', 9);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Book Flight Tickets', 'Book round-trip flight tickets for upcoming vacation', '2024-03-01', 'High', 'To Do', 10);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Read Chapter 5', 'Read Chapter 5 of "The Great Gatsby" for literature class', '2024-03-05', 'Medium', 'In Progress', 6);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Pay Bills', 'Pay utility bills and credit card bills', '2024-03-10', 'High', 'To Do', 8);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Attend Yoga Class', 'Attend the 6 PM yoga class at the local studio', '2024-03-15', 'Medium', 'To Do', 4);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Write Blog Post', 'Write a blog post on the latest technology trends', '2024-03-20', 'High', 'To Do', 12);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Plan Weekend Trip', 'Plan a weekend getaway to the mountains', '2024-03-25', 'Medium', 'In Progress', 10);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Call Mom', 'Call mom to catch up and share updates', '2024-03-30', 'Low', 'To Do', 13);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Complete Online Course', 'Finish the last module of the online course on web development', '2024-04-05', 'High', 'In Progress', 6);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Attend Networking Event', 'Attend the local tech meetup for networking', '2024-04-10', 'Medium', 'Done', 10);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Painting Session', 'Have a painting session to relax and unwind', '2024-04-15', 'Low', 'In Progress', 7);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Update Resume', 'Update resume with recent achievements and projects', '2024-04-20', 'High', 'Done', 1);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Organize Home Office', 'Declutter and organize the home office space', '2024-04-25', 'Medium', 'In Progress', 5);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Learn a New Recipe', 'Try cooking a new recipe for dinner', '2024-05-01', 'Low', 'To Do', 19);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Start Book Club', 'Initiate a book club with friends and pick the first book', '2024-05-05', 'High', 'To Do', 15);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Practice Guitar', 'Spend 30 minutes practicing the guitar', '2024-05-10', 'Medium', 'Done', 11);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Volunteer at Local Shelter', 'Offer time to volunteer at the local animal shelter', '2024-05-15', 'High', 'To Do', 14);
INSERT INTO task (title, description, due_date, priority, status, category_id) VALUES ('Visit Art Exhibition', 'Attend the art exhibition at the city gallery', '2024-05-20', 'Medium', 'Done', 6);

INSERT INTO address (street, city, zip_code) VALUES ('123 Main St', 'New York', '10001');
INSERT INTO address (street, city, zip_code) VALUES ('456 Oak St', 'Los Angeles', '90001');
INSERT INTO address (street, city, zip_code) VALUES ('789 Pine St', 'Chicago', '60601');
INSERT INTO address (street, city, zip_code) VALUES ('101 Elm St', 'San Francisco', '94105');
INSERT INTO address (street, city, zip_code) VALUES ('202 Maple St', 'Houston', '77002');
INSERT INTO address (street, city, zip_code) VALUES ('303 Cedar St', 'Miami', '33101');
INSERT INTO address (street, city, zip_code) VALUES ('404 Birch St', 'Dallas', '75201');
INSERT INTO address (street, city, zip_code) VALUES ('505 Walnut St', 'Atlanta', '30301');
INSERT INTO address (street, city, zip_code) VALUES ('606 Spruce St', 'Seattle', '98101');
INSERT INTO address (street, city, zip_code) VALUES ('707 Ash St', 'Boston', '02101');
INSERT INTO address (street, city, zip_code) VALUES ('808 Pine St', 'Denver', '80202');
INSERT INTO address (street, city, zip_code) VALUES ('909 Oak St', 'Philadelphia', '19102');
INSERT INTO address (street, city, zip_code) VALUES ('1010 Maple St', 'Phoenix', '85001');
INSERT INTO address (street, city, zip_code) VALUES ('1111 Elm St', 'San Diego', '92101');
INSERT INTO address (street, city, zip_code) VALUES ('1212 Cedar St', 'Austin', '73301');
INSERT INTO address (street, city, zip_code) VALUES ('1313 Birch St', 'Portland', '97201');
INSERT INTO address (street, city, zip_code) VALUES ('1414 Walnut St', 'Nashville', '37201');
INSERT INTO address (street, city, zip_code) VALUES ('1515 Spruce St', 'San Antonio', '78201');
INSERT INTO address (street, city, zip_code) VALUES ('1616 Ash St', 'Las Vegas', '89101');
INSERT INTO address (street, city, zip_code) VALUES ('1717 Pine St', 'Minneapolis', '55401');
INSERT INTO address (street, city, zip_code) VALUES ('1818 Oak St', 'Detroit', '48201');

INSERT INTO members (name, surname, email, password, address_id) VALUES ('John', 'Doe', 'admin@admin.com', '$2a$13$9kqnZ.VftG7t2z7R5LiVJeMDZ1/lWbbI/XjoNtoGsyvlupmKrBfri', 1);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Jane', 'Smith', 'jane.smith@example.com', '$2a$12$d0oZz3ZRpKrYlvqIKM/OGuf9UGnqm4arvvFiJF.BVDKU8GggKS7NS', 2);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Alice', 'Johnson', 'alice.johnson@example.com', '$2a$12$d0oZz3ZRpKrYlvqIKM/OGuf9UGnqm4arvvFiJF.BVDKU8GggKS7NS', 3);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Bob', 'Miller', 'bob.miller@example.com', 'dqs', 4);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Emily', 'Jones', 'emily.jones@example.com', 'password5', 5);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('David', 'Williams', 'david.williams@example.com', 'password6', 6);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Olivia', 'Brown', 'olivia.brown@example.com', 'password7', 7);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Michael', 'Taylor', 'michael.taylor@example.com', 'password8', 8);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Sophia', 'Moore', 'sophia.moore@example.com', 'password9', 9);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Daniel', 'Clark', 'daniel.clark@example.com', 'password10', 10);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Emma', 'Lee', 'emma.lee@example.com', 'password11', 11);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Matthew', 'White', 'matthew.white@example.com', 'password12', 12);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Ava', 'Anderson', 'ava.anderson@example.com', 'password13', 13);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('William', 'Harris', 'william.harris@example.com', 'password14', 14);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Ella', 'Martin', 'ella.martin@example.com', 'password15', 15);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('James', 'Thompson', 'james.thompson@example.com', 'password16', 16);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Amelia', 'Garcia', 'amelia.garcia@example.com', 'password17', 17);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Benjamin', 'Rodriguez', 'benjamin.rodriguez@example.com', 'password18', 18);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Mia', 'Lopez', 'mia.lopez@example.com', 'password19', 19);
INSERT INTO members (name, surname, email, password, address_id) VALUES ('Logan', 'Martinez', 'logan.martinez@example.com', 'password20', 20);

INSERT INTO assignment (task_id, members_id) VALUES (1, 1);
INSERT INTO assignment (task_id, members_id) VALUES (2, 2);
INSERT INTO assignment (task_id, members_id) VALUES (2, 2);
INSERT INTO assignment (task_id, members_id) VALUES (2, 2);
INSERT INTO assignment (task_id, members_id) VALUES (5, 5);
INSERT INTO assignment (task_id, members_id) VALUES (6, 6);
INSERT INTO assignment (task_id, members_id) VALUES (7, 7);
INSERT INTO assignment (task_id, members_id) VALUES (8, 8);
INSERT INTO assignment (task_id, members_id) VALUES (9, 9);
INSERT INTO assignment (task_id, members_id) VALUES (10, 10);
INSERT INTO assignment (task_id, members_id) VALUES (11, 11);
INSERT INTO assignment (task_id, members_id) VALUES (12, 12);
INSERT INTO assignment (task_id, members_id) VALUES (13, 13);
INSERT INTO assignment (task_id, members_id) VALUES (14, 14);
INSERT INTO assignment (task_id, members_id) VALUES (15, 15);
INSERT INTO assignment (task_id, members_id) VALUES (16, 16);
INSERT INTO assignment (task_id, members_id) VALUES (17, 17);
INSERT INTO assignment (task_id, members_id) VALUES (18, 18);
INSERT INTO assignment (task_id, members_id) VALUES (19, 19);
INSERT INTO assignment (task_id, members_id) VALUES (20, 20);

INSERT INTO role (name) VALUES ('ADMIN');
INSERT INTO role (name) VALUES ('USER');

INSERT INTO user_roles (members_id, role_id) VALUES (1, 2);
INSERT INTO user_roles (members_id, role_id) VALUES (2, 2);
INSERT INTO user_roles (members_id, role_id) VALUES (3, 2);

INSERT INTO assignment (task_id, members_id) VALUES (1, 1);
INSERT INTO assignment (task_id, members_id) VALUES (2, 2);
INSERT INTO assignment (task_id, members_id) VALUES (3, 1);